#ifndef RESPONSES_H
# define RESPONSES_H

# define RPL_WELCOME "001"
# define RPL_YOURHOST "002"
# define RPL_CREATED "003"
# define RPL_MYINFO "004"
# define RPL_UMODEIS "221"
# define RPL_LIST "322"
# define RPL_LISTEND "323"
# define RPL_YOUROPER "381"

# define ERR_NOSUCHSERVER "402"
# define ERR_TOOMANYMATCHES "416"
# define ERR_NONICKNAMEGIVEN "431"
# define ERR_ERRONEUSNICKNAME "432"
# define ERR_NICKNAMEINUSE "433"
# define ERR_NICKCOLLISION "436"
# define ERR_UNAVAILRESOURCE "437"
# define ERR_NEEDMOREPARAMS "461"
# define ERR_ALREADYREGISTRED "462"
# define ERR_PASSWDMISMATCH "464"
# define ERR_RESTRICTED "484"
# define ERR_NOOPERHOST "491"
# define ERR_UMODEUNKNOWNFLAG "501"
# define ERR_USERSDONTMATCH "502"

#endif